<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorkTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [
            [
                'tua_de' => 'Điều Kì Diệu Của Tiệm Tạp Hóa Namiya (Tái bản)',
                'tac_gia' => 'Higashimo Keigo',
                'dich_gia' => 'Phương Nam',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Hội Nhà Văn',
                'nam_xuat_ban' => '2021',
                'tong_bien_tap' => 'Nguyễn Quang Thiều',
                'bien_tap_vien' => 'Đào Bá Đoàn',
                'so_dkxb' => '1292-2021/CXBIPH/32-27/HNV',
                'so_qdxb' => '1042/QĐ-NXB HNV',
                'ngay_cap_qdxb' => '2021-10-1',
                'ma_so_isbn' => '978-604-391-971-0',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'dieu_ky_dieu_cua_tiem_tap_hoa_namiya.png',
                'mo_ta_noi_dung' => 'Một đêm vội vã lẩn trốn sau phi vụ khoắng đồ nhà người, Atsuya, Shota, Kouhei đã rẽ vào lánh tạm trong một căn nhà hoang bên con dốc vắng người qua lại. Căn nhà có vẻ khi xưa là một tiệm tạp hóa với biển hiệu cũ kỹ bám đầy bồ hóng, khiến người ta khó lòng đọc được trên đó viết gì. Định bụng nghỉ tạm một đêm rồi sáng hôm sau chuồn sớm, cả ba không ngờ chờ đợi cả bọn sẽ là một đêm không ngủ, với bao điều kỳ bí bắt đầu từ một phong thư bất ngờ gửi đến.'. PHP_EOL .'Tài kể chuyện hơn người đã giúp Keigo khóe léo thay đổi các mốc dấu thời gian và khôgn gian, chắp nối những câu chuyện tưởng chừng hoàn toàn riêng rẽ thành một kết cấu chặt chẽ, gây bất ngờ từ đầu tới cuối.',
                'tai_khoan_dang_tai' => '2',
                'trang_thai' => '1',
                'ban_quyen' => '4',
            ],
            [
                'tua_de' => 'Suối Nguồn Tươi Trẻ - Quyển 2',
                'tac_gia' => 'Peter Kelder',
                'dich_gia' => 'Phạm Thùy Dương',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Tổng Hợp Thành phố Hồ Chí Minh',
                'nam_xuat_ban' => '2020',
                'tong_bien_tap' => 'Đinh Thị Thanh Thủy',
                'bien_tap_vien' => 'Nguyễn Văn Sướng',
                'so_dkxb' => '4129-2020/CXBIPH/05-281/THTPHCM',
                'so_qdxb' => '835/QĐ-THTPHCM-2020',
                'ngay_cap_qdxb' => '2020-10-16',
                'ma_so_isbn' => '978-604-312-066-0',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'suoi_nguon_tuoi_tre.png',
                'mo_ta_noi_dung' => 'Cuốn sách này sẽ giới thiệu đến bạn những ý tưởng, kỹ thuật và minh triết có thể giúp bạn tăng cường sức mạnh, nâng cao sức khỏe, gia tăng niềm vui sống và giúp bạn sống lâu hơn.\nBạn cũng sẽ tìm thấy một lượng lớn thông tin liên quan đến chế độ ăn uống, cách hít thở, năng lượng học của giọng nói và nhiều chủ đề khác. Bạn sẽ đọc được những trải nghiệm đầy cảm hứng từ những người đã và đang thực hành năm thức tập này. Ngoài ra, bạn còn tìm thấy những lời khuyên và kiến thức tinh thông được chia sẻ bởi các bác sĩ và nhà trị liệu.'. PHP_EOL .'-Bernie S.Siegel, bác sĩ y khoa',
                'tai_khoan_dang_tai' => '8',
                'trang_thai' => '1',
                'ban_quyen' => '2',
            ],
            [
                'tua_de' => 'Thông Điệp Của Nước',
                'tac_gia' => 'Masuru Emoto',
                'dich_gia' => 'Thanh Huyền',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Lao Động',
                'nam_xuat_ban' => '2023',
                'tong_bien_tap' => 'Mai Thị Thanh Hằng',
                'bien_tap_vien' => 'Lê Thị Hằng',
                'so_dkxb' => '667-2023/CXBIPH/15-39/LĐ',
                'so_qdxb' => '208/QĐ-NXBLĐ',
                'ngay_cap_qdxb' => '2023-09-03',
                'ma_so_isbn' => '978-604-393-263-8',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'thong_diep_cua_nuoc.png',
                'mo_ta_noi_dung' => 'Cuốn sách có khả năng thay đổi sâu sắc thế giới quan của bạn. Tiến sĩ Masaru Emoto phát hiện ra rằng những tinh thể hình thành từ nước đóng băng có khả năng thay đổi để biểu lộ những suy nghĩ đặc biệt và tập trung hướng về "chúng". Ông phát hiện ra rằng nước từ những dòng suối trong sạch và nước được tiếp xúc với những ngôn từ đáng yêu hiển thị những hình mẫu rực rỡ, tinh tế, tuyệt đẹp. Ngược lại, nước ô nhiễm hay nước tiếp xúc với những suy nghĩ tiêu cực sẽ tạo thành những tinh thể thiếu hoán chỉnh, bất đối xứng hoặc không hình thành tinh thể. Những phát hiện này sẽ thay đổi cách nhìn nhận và tác động của chúng ta lên bản thân mình và thế giới xung quanh theo hướng tích cực hơn.',
                'tai_khoan_dang_tai' => '1',
                'trang_thai' => '1',
                'ban_quyen' => '3',
            ],
            [
                'tua_de' => 'Mắt Biếc',
                'tac_gia' => 'Nguyễn Nhật Ánh',
                'dich_gia' => '',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Trẻ',
                'nam_xuat_ban' => '2017',
                'tong_bien_tap' => 'Nguyễn Minh Nhựt',
                'bien_tap_vien' => 'Trần Thị Khánh',
                'so_dkxb' => '589-2017/CXBIPH/27-33/Tre',
                'so_qdxb' => '329/QĐ-NXBT',
                'ngay_cap_qdxb' => '2017-6-5',
                'ma_so_isbn' => '978-604-1-00514-3',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'mat_biec.png',
                'mo_ta_noi_dung' => 'Tôi không thể bắt Hà Lan phải giống tôi. Tôi khác, Không ai bắt tôi phải hoài vọng kỷ niệm. Không ai bắt tôi phải nhớ da diết cái làng xa xăm của mình mỗi khi chiều xuống. Không ai bắt tôi đêm nào cũng phải mơ thấy bóng trăng tuổi thơ treo lơ lửng trên đường làng và rơi từng giọt vàng xuống giàn hoa thiên lý. Những điều đó xảy đến một cách tự nhiên, cũng giống như hồi học lớp chín, một hôm nhìn vào mắt Hà Lan, lần đầu tiên tôi cảm thấy lòng mình dậy sóng. Mà chẳng hiểu vì sao.',
                'tai_khoan_dang_tai' => '1',
                'trang_thai' => '1',
                'ban_quyen' => '5',
            ],
            [
                'tua_de' => 'Sau Lưng Một Vạt Nắng (Tái bản có bổ sung)',
                'tac_gia' => 'Fuyu',
                'dich_gia' => '',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Văn Học',
                'nam_xuat_ban' => '2015',
                'tong_bien_tap' => 'Nguyễn Anh Vũ',
                'bien_tap_vien' => 'Thạch Thị Toàn',
                'so_dkxb' => '3057-2015/CXBIPH/11-223/VH',
                'so_qdxb' => '2015-10-16',
                'ngay_cap_qdxb' => '2015-11-2',
                'ma_so_isbn' => '978-604-69-7149-8',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'sau_lung_mot_vat_nang.png',
                'mo_ta_noi_dung' => 'Phía sau một vạt nắng có thể là chút vương vấn trong đêm rồi tan biến vào sáng sớm như sương. Hay nỗi buồn xám xịt, sũng nước, dai dẳng như một cơn mưa mà dẫu mưa đã tạnh, cảm giác ẩm ướt hãy còn vương trên tóc. Cũng có khi là nỗi nhớ xếp chồng theo ngày tháng, như chiếc bánh dâu tây ngàn lớp trong tủ kính phảng phất vị ngọt và chua...'. PHP_EOL .'Nhưng khi tất cả đã đi qua rồi, chỉ còn đọng lại một vạt nắng luôn luôn tươi tắn.'. PHP_EOL .'Đủ khiến bạn mỉm cười.',
                'tai_khoan_dang_tai' => '2',
                'trang_thai' => '1',
                'ban_quyen' => '5',
            ],
            [
                'tua_de' => 'Ngày Anh Không Tìm Em Trong Thành Phố',
                'tac_gia' => 'Đàm Huy Đông',
                'dich_gia' => '',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Văn Học',
                'nam_xuat_ban' => '2016',
                'tong_bien_tap' => 'Nguyễn Anh Vũ',
                'bien_tap_vien' => 'Nguyễn Thu Hà',
                'so_dkxb' => '148-2016/CXBIPH/05-14/VH',
                'so_qdxb' => '491/QĐ-VH',
                'ngay_cap_qdxb' => '2016-3-14',
                'ma_so_isbn' => '978-604-69-7782-7',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'ngay_anh_khong_tim_em_trong_thanh_pho.png',
                'mo_ta_noi_dung' => '"Em ở đâu cho tôi được đến tìm?'. PHP_EOL .'Mùa hạ ép con ve khô xác'. PHP_EOL .'Bằng lăng tím tư bao giờ còn ngơ ngác'. PHP_EOL .'Em về đâu sau giờ học cuối cùng?'. PHP_EOL .'Có bao giờ em hiểu tôi không?'. PHP_EOL .'Tim tôi đập rung trong tầng đá lạnh'. PHP_EOL .'Em yên lặng em bước qua kiêu hãnh'. PHP_EOL .'Tôi nghe lòng nhức nhối phía xa xôi."',
                'tai_khoan_dang_tai' => '1',
                'trang_thai' => '1',
                'ban_quyen' => '5',
            ],
            [
                'tua_de' => 'Điều Kì Diệu Của Tiệm Tạp Hóa Namiya (Tái bản)',
                'tac_gia' => 'Higashimo Keigo',
                'dich_gia' => 'Phương Nam',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Hội Nhà Văn',
                'nam_xuat_ban' => '2021',
                'tong_bien_tap' => 'Nguyễn Quang Thiều',
                'bien_tap_vien' => 'Đào Bá Đoàn',
                'so_dkxb' => '1292-2021/CXBIPH/32-27/HNV',
                'so_qdxb' => '1042/QĐ-NXB HNV',
                'ngay_cap_qdxb' => '2021-10-1',
                'ma_so_isbn' => '978-604-391-971-0',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'dieu_ky_dieu_cua_tiem_tap_hoa_namiya.png',
                'mo_ta_noi_dung' => 'Một đêm vội vã lẩn trốn sau phi vụ khoắng đồ nhà người, Atsuya, Shota, Kouhei đã rẽ vào lánh tạm trong một căn nhà hoang bên con dốc vắng người qua lại. Căn nhà có vẻ khi xưa là một tiệm tạp hóa với biển hiệu cũ kỹ bám đầy bồ hóng, khiến người ta khó lòng đọc được trên đó viết gì. Định bụng nghỉ tạm một đêm rồi sáng hôm sau chuồn sớm, cả ba không ngờ chờ đợi cả bọn sẽ là một đêm không ngủ, với bao điều kỳ bí bắt đầu từ một phong thư bất ngờ gửi đến.'. PHP_EOL .'Tài kể chuyện hơn người đã giúp Keigo khóe léo thay đổi các mốc dấu thời gian và khôgn gian, chắp nối những câu chuyện tưởng chừng hoàn toàn riêng rẽ thành một kết cấu chặt chẽ, gây bất ngờ từ đầu tới cuối.',
                'tai_khoan_dang_tai' => '2',
                'trang_thai' => '1',
                'ban_quyen' => '4',
            ],
            [
                'tua_de' => 'Suối Nguồn Tươi Trẻ - Quyển 2',
                'tac_gia' => 'Peter Kelder',
                'dich_gia' => 'Phạm Thùy Dương',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Tổng Hợp Thành phố Hồ Chí Minh',
                'nam_xuat_ban' => '2020',
                'tong_bien_tap' => 'Đinh Thị Thanh Thủy',
                'bien_tap_vien' => 'Nguyễn Văn Sướng',
                'so_dkxb' => '4129-2020/CXBIPH/05-281/THTPHCM',
                'so_qdxb' => '835/QĐ-THTPHCM-2020',
                'ngay_cap_qdxb' => '2020-10-16',
                'ma_so_isbn' => '978-604-312-066-0',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'suoi_nguon_tuoi_tre.png',
                'mo_ta_noi_dung' => 'Cuốn sách này sẽ giới thiệu đến bạn những ý tưởng, kỹ thuật và minh triết có thể giúp bạn tăng cường sức mạnh, nâng cao sức khỏe, gia tăng niềm vui sống và giúp bạn sống lâu hơn.\nBạn cũng sẽ tìm thấy một lượng lớn thông tin liên quan đến chế độ ăn uống, cách hít thở, năng lượng học của giọng nói và nhiều chủ đề khác. Bạn sẽ đọc được những trải nghiệm đầy cảm hứng từ những người đã và đang thực hành năm thức tập này. Ngoài ra, bạn còn tìm thấy những lời khuyên và kiến thức tinh thông được chia sẻ bởi các bác sĩ và nhà trị liệu.'. PHP_EOL .'-Bernie S.Siegel, bác sĩ y khoa',
                'tai_khoan_dang_tai' => '8',
                'trang_thai' => '1',
                'ban_quyen' => '2',
            ],
            [
                'tua_de' => 'Thông Điệp Của Nước',
                'tac_gia' => 'Masuru Emoto',
                'dich_gia' => 'Thanh Huyền',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Lao Động',
                'nam_xuat_ban' => '2023',
                'tong_bien_tap' => 'Mai Thị Thanh Hằng',
                'bien_tap_vien' => 'Lê Thị Hằng',
                'so_dkxb' => '667-2023/CXBIPH/15-39/LĐ',
                'so_qdxb' => '208/QĐ-NXBLĐ',
                'ngay_cap_qdxb' => '2023-09-03',
                'ma_so_isbn' => '978-604-393-263-8',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'thong_diep_cua_nuoc.png',
                'mo_ta_noi_dung' => 'Cuốn sách có khả năng thay đổi sâu sắc thế giới quan của bạn. Tiến sĩ Masaru Emoto phát hiện ra rằng những tinh thể hình thành từ nước đóng băng có khả năng thay đổi để biểu lộ những suy nghĩ đặc biệt và tập trung hướng về "chúng". Ông phát hiện ra rằng nước từ những dòng suối trong sạch và nước được tiếp xúc với những ngôn từ đáng yêu hiển thị những hình mẫu rực rỡ, tinh tế, tuyệt đẹp. Ngược lại, nước ô nhiễm hay nước tiếp xúc với những suy nghĩ tiêu cực sẽ tạo thành những tinh thể thiếu hoán chỉnh, bất đối xứng hoặc không hình thành tinh thể. Những phát hiện này sẽ thay đổi cách nhìn nhận và tác động của chúng ta lên bản thân mình và thế giới xung quanh theo hướng tích cực hơn.',
                'tai_khoan_dang_tai' => '1',
                'trang_thai' => '1',
                'ban_quyen' => '3',
            ],
            [
                'tua_de' => 'Mắt Biếc',
                'tac_gia' => 'Nguyễn Nhật Ánh',
                'dich_gia' => '',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Trẻ',
                'nam_xuat_ban' => '2017',
                'tong_bien_tap' => 'Nguyễn Minh Nhựt',
                'bien_tap_vien' => 'Trần Thị Khánh',
                'so_dkxb' => '589-2017/CXBIPH/27-33/Tre',
                'so_qdxb' => '329/QĐ-NXBT',
                'ngay_cap_qdxb' => '2017-6-5',
                'ma_so_isbn' => '978-604-1-00514-3',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'mat_biec.png',
                'mo_ta_noi_dung' => 'Tôi không thể bắt Hà Lan phải giống tôi. Tôi khác, Không ai bắt tôi phải hoài vọng kỷ niệm. Không ai bắt tôi phải nhớ da diết cái làng xa xăm của mình mỗi khi chiều xuống. Không ai bắt tôi đêm nào cũng phải mơ thấy bóng trăng tuổi thơ treo lơ lửng trên đường làng và rơi từng giọt vàng xuống giàn hoa thiên lý. Những điều đó xảy đến một cách tự nhiên, cũng giống như hồi học lớp chín, một hôm nhìn vào mắt Hà Lan, lần đầu tiên tôi cảm thấy lòng mình dậy sóng. Mà chẳng hiểu vì sao.',
                'tai_khoan_dang_tai' => '1',
                'trang_thai' => '1',
                'ban_quyen' => '5',
            ],
            [
                'tua_de' => 'Sau Lưng Một Vạt Nắng (Tái bản có bổ sung)',
                'tac_gia' => 'Fuyu',
                'dich_gia' => '',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Văn Học',
                'nam_xuat_ban' => '2015',
                'tong_bien_tap' => 'Nguyễn Anh Vũ',
                'bien_tap_vien' => 'Thạch Thị Toàn',
                'so_dkxb' => '3057-2015/CXBIPH/11-223/VH',
                'so_qdxb' => '2015-10-16',
                'ngay_cap_qdxb' => '2015-11-2',
                'ma_so_isbn' => '978-604-69-7149-8',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'sau_lung_mot_vat_nang.png',
                'mo_ta_noi_dung' => 'Phía sau một vạt nắng có thể là chút vương vấn trong đêm rồi tan biến vào sáng sớm như sương. Hay nỗi buồn xám xịt, sũng nước, dai dẳng như một cơn mưa mà dẫu mưa đã tạnh, cảm giác ẩm ướt hãy còn vương trên tóc. Cũng có khi là nỗi nhớ xếp chồng theo ngày tháng, như chiếc bánh dâu tây ngàn lớp trong tủ kính phảng phất vị ngọt và chua...'. PHP_EOL .'Nhưng khi tất cả đã đi qua rồi, chỉ còn đọng lại một vạt nắng luôn luôn tươi tắn.'. PHP_EOL .'Đủ khiến bạn mỉm cười.',
                'tai_khoan_dang_tai' => '2',
                'trang_thai' => '1',
                'ban_quyen' => '5',
            ],
            [
                'tua_de' => 'Ngày Anh Không Tìm Em Trong Thành Phố',
                'tac_gia' => 'Đàm Huy Đông',
                'dich_gia' => '',
                'ngon_ngu' => 'Tiếng Việt',
                'nha_xuat_ban' => 'Nhà xuất bản Văn Học',
                'nam_xuat_ban' => '2016',
                'tong_bien_tap' => 'Nguyễn Anh Vũ',
                'bien_tap_vien' => 'Nguyễn Thu Hà',
                'so_dkxb' => '148-2016/CXBIPH/05-14/VH',
                'so_qdxb' => '491/QĐ-VH',
                'ngay_cap_qdxb' => '2016-3-14',
                'ma_so_isbn' => '978-604-69-7782-7',
                'tep_tin' => 'truyen1.docx',
                'anh_bia' => 'ngay_anh_khong_tim_em_trong_thanh_pho.png',
                'mo_ta_noi_dung' => '"Em ở đâu cho tôi được đến tìm?'. PHP_EOL .'Mùa hạ ép con ve khô xác'. PHP_EOL .'Bằng lăng tím tư bao giờ còn ngơ ngác'. PHP_EOL .'Em về đâu sau giờ học cuối cùng?'. PHP_EOL .'Có bao giờ em hiểu tôi không?'. PHP_EOL .'Tim tôi đập rung trong tầng đá lạnh'. PHP_EOL .'Em yên lặng em bước qua kiêu hãnh'. PHP_EOL .'Tôi nghe lòng nhức nhối phía xa xôi."',
                'tai_khoan_dang_tai' => '1',
                'trang_thai' => '1',
                'ban_quyen' => '5',
            ],
        ];

        DB::table('works')->insert($data);
    }
}
